### PR TITLE
Fix text NER evaluation

### PR DESCRIPTION
**Pull request by siddalmia**
Following the PR in https://github.com/asappresearch/slue-toolkit/pull/5. I started testing the evaluation pipeline for the text NER and it seems to also be quite flaky. I have fixed most of the errors but there are some critical ones that I mention in https://github.com/asappresearch/slue-toolkit/issues/6.

If you could make the edits to this PR for handling the remaining todos mentioned in the issue. That would be great. 

I have currently kept my previous PRs also committed to this one but happy to remove them once you merge those. 

Thanks
Sid

### CODE REVIEW

**Review by ankitapasad — APPROVED** [review]
LGTM

**Review by ankitapasad — APPROVED** [review]
LGTM

The conflicts are mostly because some of the suggested changes are already accounted for in the updated repo but on different lines. Let me know if there's any case otherwise.

@sshon-asapp @fwu-asapp

**Comment by sshon-asapp** [comment]
@siddalmia Given that PR #10 merged, can you update the conflict files?

**Comment by fwu-asapp** [comment]
Hi @siddalmia @sshon-asapp 
Is there any reason for changing "datasets" to "dataset" in this PR? If there is no special reason, I would just keep it as "datasets"; Otherwise, it may affect other people who have cloned the repo and are using it.

**Comment by siddalmia** [comment]
> Hi @siddalmia @sshon-asapp Is there any reason for changing "datasets" to "dataset" in this PR? If there is no special reason, I would just keep it as "datasets"; Otherwise, it may affect other people who have cloned the repo and are using it.

Yeah it's actually because huggingface which is needed for your baselines has a library called datasets. I have detailed it here - https://github.com/asappresearch/slue-toolkit/pull/5

**Comment by fwu-asapp** [comment]
@siddalmia Thanks for the clarification, nice catch! Do you mind to change it to `data` instead? Just to avoid people accidentally typing "dataset" into "datasets" or vice versa.  
@sshon-asapp what do you think?

**Comment by sshon-asapp** [comment]
Good idea. Let move away from dataset and datasets, and use `data`.

**Comment by fwu-asapp** [comment]
I renamed "datasets" to "data" in this PR #14. @siddalmia would you please resolve the conflicts? We can merge your PR once there are no conflicts left.

**Comment by siddalmia** [comment]
@fwu-asapp I will do it soon.

But this is really bad practice. The PRs that were merged after my PR were working out of this. So ideally this PR should have been merged before those ones, specially given that they are working on top of this PR.

**Comment by sshon-asapp** [comment]
@siddalmia Feel sorry about this. As you may know, this toolkit is in a very early state right now, and the original authors are fixing it as quickly as possible to provide a better experience.

**Comment by siddalmia** [comment]
@sshon-asapp @fwu-asapp I have merged this PR to the latest commit.

**Comment by fwu-asapp** [comment]
@siddalmia Thanks!
@ankitapasad  and @sshon-asapp If there is not additional concerns, we can merge this branch.

**Pull request merged**
